import Header from "../components/Header";
import { Inter } from "next/font/google";
import "./globals.css";
import { Authprovider } from "@/components/Authprovider/Authprovider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <main>
          <Header /> 
          <div className="max-w-4xl mx-auto p-6">
            <Authprovider> 
              {children}
            </Authprovider>
          </div>
        </main>
        
      </body>
    </html>
  );
}
