import { Toaster } from "react-hot-toast";
import Header from "../../components/Header";
import "../globals.css";
import { Authprovider } from "@/components/authprovider/Authprovider";
import {Lato} from 'next/font/google'

const lato = Lato({ subsets: ['latin'], weight: ['400', '700'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lato.className}> 

        <Toaster />

        <main>
          <Header /> 
          <div className="max-w-4xl mx-auto p-6">
            
            <Authprovider> 
              {children}
            </Authprovider>
          </div>
        </main>
        
      </body>
    </html>
  );
}
